#!/bin/bash

sudo apt install podman crun
if grep -E "$(whoami):[[:digit:]]+:65536" /etc/subuid >/dev/null; then
  echo "/etc/subuid already configured."
  else
    sudo touch /etc/subuid
      start_uid=$(cut -sd ":" -f "2,3" < /etc/subuid | tr ":" "+" | bc | sort -n | tail -n 1)
        sudo usermod --add-subuids ${start_uid:=100000}-$(( ${start_uid:=100000} + "65535" )) $(whoami)
	fi
	if grep -E "$(whoami):[[:digit:]]+:65536" /etc/subgid >/dev/null; then
	  echo "/etc/subgid already configured."
	  else
	    sudo touch /etc/subgid
	      start_gid=$(cut -sd ":" -f "2,3" < /etc/subgid | tr ":" "+" | bc | sort -n | tail -n 1)
	        sudo usermod --add-subgids ${start_gid:=100000}-$(( ${start_gid:=100000} + "65535" )) $(whoami)
		fi
		podman system migrate

		# If you want to use runc, run `sudo apt install runc` instead
		# mkdir -p ~/.config/containers
		# container_conf=~/.config/containers/containers.conf
		# touch "${container_conf}"
		# if grep 'cgroup_manager = "cgroupfs"' "${container_conf}" >/dev/null; then
		#   echo "${container_conf} already configured to use cgroupfs"
		#   else
		#     cat <<EOF >> "${container_conf}"
		#     [engine]
		#     #runtime = "/usr/bin/crun"
		#     cgroup_manager = "cgroupfs"
		#     EOF
		#     fi
		#
